spring.application.name=springbootaop1

# H2 DB for test application settings
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:springbootaopt1
spring.datasource.username=test
spring.datasource.password=test
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true

# Logging settings
logging.level.root=INFO
logging.file.name=logging-test-springbootaopt1.log
