-- Для тестирования! Убрать при использовании
DROP TABLE IF EXISTS account, order_details;

CREATE TABLE IF NOT EXISTS account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    CONSTRAINT pk_account PRIMARY KEY (id),
    CONSTRAINT uq_account_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS order_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR NOT NULL,
    status VARCHAR NOT NULL,
    initiator_id BIGINT NOT NULL,
    CONSTRAINT pk_order_details PRIMARY KEY (id),
    CONSTRAINT fk_initiator FOREIGN KEY (initiator_id) REFERENCES account(id) ON DELETE CASCADE
);